### ISSUE TITLE
UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host plex port 22: Connection timed out"

### ISSUE THREAD

**Issue by Reznorzo** [engonzal/ansible_role_package#1]
Container is created, and starts, but unable to connect to install packages

Full playbook example:

`--
- name: Test CT Creation Play
  hosts: proxmox
  connection: local
  user: root
  vars:
    pve_node: pve2
    pve_apiuser: root@pam
    pve_apipass: password
    pve_api_host: pve2.localdomain
    pve_hostname: "plex"
    pve_template: local:vztmpl/ubuntu-16.04-standard_16.04.5-1_amd64.tar.gz
    pve_netif:
      net0: "name=eth0,ip=dhcp,bridge=vmbr0"
    pve_guest_pass: password
  roles:
    - name: engonzal.proxmox
      tags: pve
  post_tasks:
    - name: Pause for CT starting
      pause:
        seconds: 10

- name: Test CT Package Play
  hosts: containers
  user: root
  vars:
    package_list:
      - vim
  roles:
    - engonzal.package
`

Running with - ansible-playbook -i hosts proxmox.yml

Hosts file:
[proxmox]
pve2

[containers]
plex

**Comment by Reznorzo** [comment]
Update:
I got this working by changing the host under [containers] to its IP address and copying over my public key from the node to the container.

However, even with the key copied over it won't work when specifying the container name instead of IP

Also, I noticed you had a pve_ssh line in the ansible_role_proxmox example - does this prevent the need for copying the key over ?

pve_ssh: "ssh-rsa myPublicKey engonzal@hostname"

What are putting in place of myPublicKey ?

Thanks in advance !

**Comment by engonzal** [comment]
So usually with new containers I add the DNS record manually to OPNSense (my home router).  If you have to wait for the container to boot up, get a DHCP lease, then update DNS, you might need to give you container a little longer to boot so the dns record gets created.  Another option might be to set the ansible_host variable to the ip for the inventory item, ie:
```
[containers]
plex ansible_host=192.168.1.10
```

Yeah I use ssh keys.  So the contents of your ssh public key (typically at /home/yourusername/.ssh/id_rsa.pub) would replace "myPublicKey".  If you set that it should add the key to the authorized_keys file for root in the container.

**Comment by Reznorzo** [comment]
Brilliant thanks. Proxmox is currently running in a vmware VM whilst I figure all this stuff out. I'm in the process of building a proper lab which will have a PFSense router, with proxmox as the hypervisor on the server itself. So the whole DNS, DHCP thing will be a lot smoother then.
I've used the ansilbe_host example in the meantime. 

That worked perfectly thanks.
